# Generated by Django 5.2.1 on 2025-12-01 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0006_cosmetic_created_at_cosmetic_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='recommended_for', to='cosmetic.cosmetic'),
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
