# Generated by Django 5.2.1 on 2025-11-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cosmetic', '0002_alter_category_name_alter_cosmetic_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='cosmetic.cosmetic'),
        ),
    ]
